# Week 6 – Worksheet: Mini Contact Book Assignment

## Part A — Basics

### A1. Create a dictionary containing at least 3 contacts.

In [8]:
# TODO: Create a dictionary called `contact_book` with at least 3 contacts.
# Each contact will have a name (key) and a phone number (value).
# Using unique Australian-style names and phone numbers.
contact_book = {
    "Elara Vance": "0435 123 456",
    "Kaelen Stone": "0401 789 012",
    "Zara Khan": "0422 345 678"
}

# Display the initial contact book to see the created contacts.
print("Initial Contact Book:")
print(contact_book)

Initial Contact Book:
{'Elara Vance': '0435 123 456', 'Kaelen Stone': '0401 789 012', 'Zara Khan': '0422 345 678'}


### Explanation of A1:

This code creates a simple dictionary called `contact_book`. In this dictionary, each person's name (like 'Elara Vance') is a unique key, and their phone number ('0435 123 456') is the value associated with that key. Dictionaries are great for storing information that comes in pairs, like names and phone numbers, because you can easily look up a phone number if you know the name.

### Example Output for A1:

```
Initial Contact Book:
{'Elara Vance': '0435 123 456', 'Kaelen Stone': '0401 789 012', 'Zara Khan': '0422 345 678'}
```

### A2. Add a new contact.

In [3]:
# TODO: Add a new contact to the `contact_book` dictionary.
# Choose a new unique name and phone number.
new_contact_name = "Rhys Anderson"
new_contact_phone = "0418 901 234"

# To add a new contact, we simply assign a value to a new key in the dictionary.
contact_book[new_contact_name] = new_contact_phone

# Display the contact book again to show the newly added contact.
print(f"\nContact Book after adding {new_contact_name}:")
print(contact_book)


Contact Book after adding Rhys Anderson:
{'Elara Vance': '0435 123 456', 'Kaelen Stone': '0401 789 012', 'Zara Khan': '0422 345 678', 'Rhys Anderson': '0418 901 234'}


### Explanation of A2:

To add a new contact to our `contact_book`, we use a simple assignment. We pick a new name, `Rhys Anderson`, and a new phone number. Then, we write `contact_book[new_contact_name] = new_contact_phone`. This tells Python to create a new entry in the dictionary with `Rhys Anderson` as the key and his phone number as the value. If `Rhys Anderson` didn't exist before, it's added. If he did, his number would be updated (but here, we're adding a new one).

### Example Output for A2:

```
Contact Book after adding Rhys Anderson:
{'Elara Vance': '0435 123 456', 'Kaelen Stone': '0401 789 012', 'Zara Khan': '0422 345 678', 'Rhys Anderson': '0418 901 234'}
```

### A3. Update an existing contact.

In [4]:
# TODO: Update an existing contact's phone number in the `contact_book` dictionary.
# Let's update Elara Vance's phone number.
existing_contact_name = "Elara Vance"
updated_phone_number = "0487 654 321"

# To update a contact, we access their name (key) and assign a new value (phone number).
contact_book[existing_contact_name] = updated_phone_number

# Display the contact book to show the updated contact.
print(f"\nContact Book after updating {existing_contact_name}'s number:")
print(contact_book)


Contact Book after updating Elara Vance's number:
{'Elara Vance': '0487 654 321', 'Kaelen Stone': '0401 789 012', 'Zara Khan': '0422 345 678', 'Rhys Anderson': '0418 901 234'}


### Explanation of A3:

Updating a contact is very similar to adding one. We specify the name of the contact we want to change, which is `Elara Vance` in this case. Then, we assign a new phone number to her entry in the `contact_book` using `contact_book[existing_contact_name] = updated_phone_number`. Since `Elara Vance` already exists as a key, Python will simply replace her old phone number with the new one we provided.

### Example Output for A3:

```
Contact Book after updating Elara Vance's number:
{'Elara Vance': '0487 654 321', 'Kaelen Stone': '0401 789 012', 'Zara Khan': '0422 345 678', 'Rhys Anderson': '0418 901 234'}
```

### A4. Use a loop to display the contacts.

In [5]:
# TODO: Use a `for` loop to iterate through the `contact_book` and display each contact.
# The output format should be 'Name: [Name], Phone: [Phone Number]'.
print("\nAll Contacts:")
# We use the `.items()` method to get both the key (name) and the value (phone number) from the dictionary.
for name, phone_number in contact_book.items():
    print(f"Name: {name}, Phone: {phone_number}")


All Contacts:
Name: Elara Vance, Phone: 0487 654 321
Name: Kaelen Stone, Phone: 0401 789 012
Name: Zara Khan, Phone: 0422 345 678
Name: Rhys Anderson, Phone: 0418 901 234


### Explanation of A4:

This code uses a `for` loop to go through every contact in our `contact_book`. The `.items()` method is handy here because it gives us both the contact's `name` (the key) and their `phone_number` (the value) in each turn of the loop. Inside the loop, we use an f-string (formatted string literal) to print out the name and phone number in a clear, easy-to-read format.

### Example Output for A4:

```
All Contacts:
Name: Elara Vance, Phone: 0487 654 321
Name: Kaelen Stone, Phone: 0401 789 012
Name: Zara Khan, Phone: 0422 345 678
Name: Rhys Anderson, Phone: 0418 901 234
```